---
title: "STAT 30850 Project Plots (v1.0)"
author: 
  - Arjun Biddanda (abiddanda@uchicago.edu)
  - Joseph Marcus (jhmarcus@uchicago.edu)
date: \today
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amsthm}
fontsize: 11pt
output: pdf_document
---


#1. Gibbs Sampler Convergence Statistics

```{r, echo=FALSE}
source("../src/simulation/simulate_mixture.R")
source("../src/model/mcmc.R")


X <- sim.mixture.2comp(1000, 0.90, mu1=2, sigma1=1)

gibbs10 <- gibbs_sampler(X$Z[1:10], 2000)
gibbs100 <- gibbs_sampler(X$Z[1:100], 2000)
gibbs500 <- gibbs_sampler(X$Z[1:500], 2000)
gibbs1000 <- gibbs_sampler(X$Z[1:1000], 2000)

par(mfrow=c(2,2))
plot(-gibbs10$trace, type='l', main="N=10", ylab="Trace")
plot(-gibbs100$trace, type='l', main="N=100", ylab="Trace")
plot(-gibbs500$trace, type='l', main="N=500", ylab="Trace")
plot(-gibbs1000$trace, type='l', main="N=1000", ylab="Trace")
```

#2. Sequential Confidence Intervals of $\mu_1$

```{r, echo=FALSE}
# Confidence Interval Function (Normally Distributed)
confidence <- function(x, a=0.05){
  xbar <- mean(x)
  s <- sqrt(var(x))
  n <- length(x)
  err <- (qnorm(1-(a/2))*s)/sqrt(n)
  return(c(xbar-err, xbar+err, xbar, s, err))
}

lower.mu1 <- c()
upper.mu1 <- c()
mean.mu1 <- c()
mean.sigma2 <- c()
upper.sigma2 <- c()

mean.pi0 <- c()
upper.pi0 <- c()

for (i in seq(from=1, to=1000, by=100)){
  cur.gibbs <- gibbs_sampler(X$Z[1:i], n_iter=2000)
  mu.conf <- confidence(cur.gibbs$mu1_samples)
  pi0.conf <- confidence(cur.gibbs$pi0_samples)
  sigma2.conf <- confidence(1/cur.gibbs$phi1_samples)
  lower.mu1 <- c(lower.mu1, mu.conf[1])
  upper.mu1 <- c(upper.mu1, mu.conf[2])
  mean.mu1 <- c(mean.mu1, mu.conf[3])
  upper.pi0 <- c(upper.pi0, pi0.conf[2])
  mean.pi0 <- c(mean.pi0, pi0.conf[3])
  upper.sigma2 <- c(upper.sigma2, sigma2.conf[2])
  mean.sigma2 <- c(mean.sigma2, sigma2.conf[3])
}

upper.sigma2[upper.sigma2 > 10] <- 10

df2 <- data.frame(x=seq(length(mean.mu1)),
                    fit=mean.mu1,lwr=lower.mu1,upr=upper.mu1)

plot(fit~x,
     data=df2,
     ylim=range(c(1,3)),
     ylab="Confint(Mu1)",
     xlab="t (x 100)")
with(df2,polygon(c(x,rev(x)),c(lwr,rev(upr)),col = "grey75", border = FALSE))
matlines(df2[,1],df2[,-1],
        lwd=c(2,1,1),
        lty=1,
        col=c("black","red","red"))

```


#3. Estimates of BayesFDR sequentially over time

```{r, echo=FALSE}
source("../src/analysis/fdr_methods.R")
# Setting the significance threshold
alpha <- 0.1

z_hat_bayes <- get_roots(BayesFDR, alpha, mean.mu1, mean.pi0, mean.sigma2)
z_hat_bayes.max <- get_roots(BayesFDR, alpha, upper.mu1, upper.pi0, upper.sigma2)

plot(z_hat_bayes, xlab="t (x 100)", ylab="Z-Bayes (using mean)", type='l')

plot(z_hat_bayes.max, xlab="t (x 100)", ylab="Z-Bayes (using upper 95th quantile)", type='l')

```
