---
title: "Online Bayesian FDR Control"
author: "Arjun Biddanda and Joseph Marcus"
date: "March 11, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Online Hypothesis Testing

TODO : describe valid scenarios when we would want to use online testing.


## Previous Methods to Control Online FDR

- LBOND / LBORD
- $\alpha$-investing

## A Bayesian Approach to FDR


## Modeling Assumptions

We will largely be working in "Z-score" space, where:

  $$Z \sim \pi\cdot N(0,1) + (1-\pi) \cdot N(\mu_1 ,\sigma^2_1)$$

## Gibbs Sampler  

- We want to estimate $\theta = \{\pi, \mu_1, \sigma^2_1\}$

- We can use a Gibbs Sampler and some conjugate priors to accomplish this!


## Simulation Scenario

- We simulate 10000 time points , and a Z-score from each time point given $\theta = \{\pi = 0.9, \mu_1 = 2, \sigma^2_1 = 1\}$

- In order to compare against previous methods such as LBOND/LBORD


## False-Positive Rates


## Power


## Caveats to Inference 

- Really difficult to estimate model parameters with small amount of data
- Iterative Gibbs Sampling can be quite intensive

## Further Directions

- 

## Acknowledgements


